apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-pfxcreator
  namespace: cert-manager
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: client_id
    azure.workload.identity/tenant-id: tenant_id
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pfxcreator-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pfxcreator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: workload-identity-pfxcreator
  namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: pfxcreator-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfxcreator
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pfxcreator
  template:
    metadata:
      labels:
        name: pfxcreator
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-pfxcreator
      containers:
      - name: pfxoperator
        image: deggja/pfxcreator:latest
        args:
          - "--leader-elect=true"
        env:
          - name: KEY_VAULT_NAME
            value: "KEY_VAULT_NAME"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
